name: Cache Bust Version Increment

on:
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Read current version
        id: read_version
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Increment version
        run: |
          OLD_VERSION=$(cat version.txt)
          IFS='.' read -r -a VERSION_PARTS <<< "$OLD_VERSION"
          VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
          echo "$NEW_VERSION" > version.txt
          echo "New version: $NEW_VERSION"

      - name: Commit and push new version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Increment version to $NEW_VERSION"
          git push
